### ISSUE TITLE
[SR-15913] Latest nightly snapshots have a broken lldb on focal

### ISSUE THREAD

**Issue by Lukasa** [swiftlang/llvm-project#4297]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-15913      |
   |Radar             | rdar://problem/89641524         |
   |Original Reporter | @Lukasa      |
   |Type              | Bug    |

<details>
  <summary>Environment</summary>

Swift version 5.7-dev (LLVM f255403e4661ee9, Swift 496da9dda967e76)  
Ubuntu 20.04.4 LTS

</details>

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @JDevlieghere      |
   |Priority          | Medium      |

   

   md5: 8343654c29713b6432fbbc6688cc4772

  </details>

**Issue Description:**

If you download and use the latest nightly snapshot from trunk for Ubuntu Focal (swift-DEVELOPMENT-SNAPSHOT-2022-02-22-a-ubuntu20.04) and try to use its lldb, you are greeted with:

``` java
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb'
```

If you install lldb from the package archive (sudo apt-get install lldb) you instead get:

``` java
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 11409, in <module>
    class SBTraceOptions(object):
  File "/usr/lib/python3/dist-packages/lldb/__init__.py", line 11468, in SBTraceOptions
    __swig_destroy__ = _lldb.delete_SBTraceOptions
AttributeError: module '_lldb' has no attribute 'delete_SBTraceOptions'
```

Both of these leave a semi-functional lldb that is incapable of symbolicating Swift backtraces.

**Comment by Lukasa** [comment]
@swift-ci create
