### ISSUE TITLE
[SR-8245] TestSwiftStepping.py and two other tests are flaky on Linux, resulting in failed PR testing

### ISSUE THREAD

**Issue by belkadan** [swiftlang/llvm-project#4366]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-8245      |
   |Radar             | rdar://problem/42145676         |
   |Original Reporter | @belkadan      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: b4fa6a107223d807552002c334a23535

  </details>

**Issue Description:**

For the last week or two (?) three LLDB tests have been failing every now and then on the Linux builds, particularly in PR testing. [Here's an example](https://ci.swift.org/job/swift-PR-Linux/6208/).

    19:00:38 FAIL: test_swift_conditional_breakpoint_dwarf (lang/swift/conditional_breakpoints/TestSwiftConditionalBreakpoint.py)
    19:00:38 FAIL: test_swift_stepping_dwarf (lang/swift/stepping/TestSwiftStepping.py)
    19:00:38 FAIL: test_swift_struct_init_dwarf (lang/swift/struct_init_display/TestSwiftStructInit.py)

It's always these three tests, so they probably have something in common. Here's the backtrace for TestSwiftStepping:

    19:00:28 ======================================================================
    19:00:28 FAIL: test_swift_stepping_dwarf (TestSwiftStepping.TestSwiftStepping)
    19:00:28    Tests that we can step reliably in swift code.
    19:00:28 ----------------------------------------------------------------------
    19:00:28 Traceback (most recent call last):
    19:00:28   File "/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1774, in dwarf_test_method
    19:00:28     return attrvalue(self)
    19:00:28   File "/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/packages/Python/lldbsuite/test/decorators.py", line 144, in wrapper
    19:00:28     func(*args, **kwargs)
    19:00:28   File "/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/packages/Python/lldbsuite/test/lang/swift/stepping/TestSwiftStepping.py", line 32, in test_swift_stepping
    19:00:28     self.do_test()
    19:00:28   File "/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/packages/Python/lldbsuite/test/lang/swift/stepping/TestSwiftStepping.py", line 120, in do_test
    19:00:28     self.hit_correct_function(thread, "toSomeValues")
    19:00:28   File "/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/packages/Python/lldbsuite/test/lang/swift/stepping/TestSwiftStepping.py", line 84, in hit_correct_function
    19:00:28     "Got to '%s' not the expected function '%s'." % (desc.GetData(), pattern))
    19:00:28 AssertionError: False is not True : Got to '/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/lldb/packages/Python/lldbsuite/test/lang/swift/stepping/main.swift:172:5' not the expected function 'toSomeValues'.
    19:00:28 Config=x86_64-/home/buildnode/jenkins/workspace/swift-PR-Linux/branch-master/buildbot_linux/llvm-linux-x86_64/bin/clang-6.0
    19:00:28 ----------------------------------------------------------------------

If there's not a quick fix, can we disable these tests on Linux for now?

**Comment by belkadan** [comment]
@swift-ci create

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
<https://github.com/apple/swift-lldb/pull/769>
