### ISSUE TITLE
[SR-6535] In-tree LLDB tests are failing as a dependency is missing

### ISSUE THREAD

**Issue by 0acf245c-f0fa-406f-afb9-4746d10f0359** [swiftlang/llvm-project#4382]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-6535      |
   |Radar             | None         |
   |Original Reporter | @dcci      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 2f2154a7be8a54dc7d6334c09a8a202b

  </details>

**Issue Description:**

Arguably this is failing because the python includes are not installed/misconfigured, but maybe cmake/build-script can error if this dependency is missing?

``` java
Command invoked: /usr/bin/python /Users/dcci/work/swift/lldb/test/dotest.py --executable /Users/dcci/work/swift/build/Ninja-RelWithDebInfoAssert/lldb-macosx-x86_64/CustomSwift-Release/lldb --rerun-all-issues -C /Users/dcci/work/swift/build/Ninja-RelWithDebInfoAssert/llvm-macosx-x86_64/bin/clang -s 2017-12-05-08_52_16 --results-port 50117 -S fnmac --inferior -p TestSourceManager.py /Users/dcci/work/swift/lldb/packages/Python/lldbsuite/test --event-add-entries worker_index=7:int
768 out of 770 test suites processed - TestSourceManager.py
/Users/dcci/work/swift/lldb/packages/Python/lldbsuite/test/crashinfo.c:15:10: fatal error: 'Python/Python.h' file not found
#include <Python/Python.h>
         ^~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/Users/dcci/work/swift/lldb/test/dotest.py", line 7, in <module>
    lldbsuite.test.run_suite()
  File "/Users/dcci/work/swift/lldb/packages/Python/lldbsuite/test/dotest.py", line 1194, in run_suite
    configuration.setupCrashInfoHook()
  File "/Users/dcci/work/swift/lldb/packages/Python/lldbsuite/test/configuration.py", line 51, in setupCrashInfoHook
    raise Exception('command failed: "{}"'.format(cmd))
Exception: command failed: "SDKROOT= xcrun clang /Users/dcci/work/swift/lldb/packages/Python/lldbsuite/test/crashinfo.c -o /Users/dcci/work/swift/lldb/packages/Python/lldbsuite/test/crashinfo.so -framework Python -Xlinker -dylib"
```

**Comment by 0acf245c-f0fa-406f-afb9-4746d10f0359** [comment]
cc: @jasonmolenda/jingham@apple.com (JIRA User)

**Comment by belkadan** [comment]
This seems like it isn't specific to Swift, except for build-script trying to detect the scenario.
