### ISSUE TITLE
[SR-1568] TestSwiftieFormatting.py failing on master and master-next

### ISSUE THREAD

**Issue by a0332500-857b-4d6a-874e-50b63b66b387** [swiftlang/llvm-project#4403]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1568      |
   |Radar             | None         |
   |Original Reporter | @trfiala      |
   |Type              | Bug    |

   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | None      |
   |Priority          | Medium      |

   

   md5: 7b4d5d2d5987adf316787e2e4e2dc335

  </details>

**Issue Description:**

This will be coming in with the merge of swift-lldb/master into swift-lldb/master-next.

======================================================================  
FAIL: test_swiftie_formatting_dsym (TestSwiftieFormatting.TestSwiftieFormatting)  
Test that data formatters honor Swift conventions  
----------------------------------------------------------------------  
Traceback (most recent call last):  
File "/Users/tfiala/src/lldb-github-next/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1456, in dsym_test_method  
return attrvalue(self)  
File "/Users/tfiala/src/lldb-github-next/lldb/packages/Python/lldbsuite/test/decorators.py", line 121, in wrapper  
func(\*args, \*\*kwargs)  
File "/Users/tfiala/src/lldb-github-next/lldb/packages/Python/lldbsuite/test/lang/swift/swiftieformatting/TestSwiftieFormatting.py", line 32, in test_swiftie_formatting  
self.do_test()  
File "/Users/tfiala/src/lldb-github-next/lldb/packages/Python/lldbsuite/test/lang/swift/swiftieformatting/TestSwiftieFormatting.py", line 110, in do_test  
self.expect('frame variable -d run nsarr\[5\] --ptr-depth=1', substrs=\['Int64(1)', 'Int64(2)', 'Int64(3)'\])  
File "/Users/tfiala/src/lldb-github-next/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1922, in expect  
msg if msg else EXP_MSG(str, output, exe))  
AssertionError: False is not True : 'frame variable -d run nsarr\[5\] --ptr-depth=1' returns expected result, got '(\_TtCs21_SwiftDeferredNSArray) nsarr\[5\] = 3 values {  
\[0\] = 1  
\[1\] = 2  
\[2\] = 3  
}'

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
This is also failing on master.

This started failing with this build and change:  
<https://ci.swift.org/job/oss-lldb-incremental-osx/3226/>

Change:  
\`\`\`  
Pending QOI improvements, reinstate implicit bridging conversions. (details)  
Commit 455aa0523dcc5f8b2e02f20a15aed084fc796a48 by jpamer  
Pending QOI improvements, reinstate implicit bridging conversions.  
The file was modified lib/Sema/CSSimplify.cpp  
The file was modified test/Constraints/bridging.swift  
\`\`\`  
[GitHub link](https://github.com/apple/swift/commit/455aa0523dcc5f8b2e02f20a15aed084fc796a48)

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Marked XFAIL here:  
\`\`\`  
commit 11c6dae1d4a070c5c7177757ff156f8f341a8e59 (HEAD -\> master, origin/master, origin/HEAD)  
Author: Todd Fiala \<tfiala@apple.com\>  
Date: Fri May 20 11:31:38 2016

mark TestSwiftieFormatting.py as XFAIL

Tracked by:  
rdar://26394885  
swift.org/SR-1568  
\`\`\`
