### ISSUE TITLE
[SR-1193] LLDB Ubuntu build error: python 'time' not defined

### ISSUE THREAD

**Issue by a0332500-857b-4d6a-874e-50b63b66b387** [swiftlang/llvm-project#4413]
|                  |                 |
   |------------------|-----------------|
   |Previous ID       | SR-1193      |
   |Radar             | None         |
   |Original Reporter | @trfiala      |
   |Type              | Bug    |
   |Status            | Closed        |
   |Resolution        | Done    |
        
   <details>
  <summary>Additional Detail from JIRA</summary>

   |                  |                 |
   |------------------|-----------------|
   |Votes             | 0         |
   |Component/s       | LLDB for Swift    |
   |Labels            | Bug        |
   |Assignee          | @trfiala      |
   |Priority          | Medium      |

   

   md5: edff2a22310212f214d596a96247cfc1

  </details>

**Issue Description:**

Looks like a simple missing import in some python module:

ERROR: test_attach_to_process_by_id_denied_dwo (TestAttachDenied.AttachDeniedTestCase)  
Test attach by process id denied  
----------------------------------------------------------------------  
Traceback (most recent call last):  
File "/home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-14_04/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1480, in dwo_test_method  
return attrvalue(self)  
File "/home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-14_04/lldb/packages/Python/lldbsuite/test/decorators.py", line 123, in wrapper  
func(\*args, \*\*kwargs)  
File "/home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-14_04/lldb/packages/Python/lldbsuite/test/functionalities/process_attach/attach_denied/TestAttachDenied.py", line 38, in test_attach_to_process_by_id_denied  
pid = lldbutil.wait_for_file_on_target(self, pid_file_path)  
File "/home/buildnode/jenkins/workspace/oss-lldb-incremental-linux-ubuntu-14_04/lldb/packages/Python/lldbsuite/test/lldbutil.py", line 1064, in wait_for_file_on_target  
time.sleep(pow(2, i) \* 0.25)  
NameError: global name 'time' is not defined  
Config=x86_64-/usr/lib/llvm-3.6/bin/clang

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Looks like we don't see this normally since it only kicks in when a test is killed due to a timeout.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Root issue:  
<http://reviews.llvm.org/D18789>

Addressing upstream now and will pull down.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
PR for change is up here:  
<https://github.com/apple/swift-lldb/pull/12>

Testing with CI now.

**Comment by a0332500-857b-4d6a-874e-50b63b66b387** [comment]
Merged in fix here:  
<https://github.com/apple/swift-lldb/commit/b2902c2acd8a857969ef62d0ef3dcce6b4656c44>
