### ISSUE TITLE
LLDB tests fail due to unexpected breakpoint sites

### ISSUE THREAD

**Issue by weliveindetail** [swiftlang/llvm-project#9540]
We see 3 tests failing for swift-lldb in CI, because of unexpected additional breakpoint sites. Failures look like this:
```
llvm-project\lldb\test\Shell\Unwind\windows-unaligned-x86_64.test:20:10: error: CHECK: expected string not found in input
# CHECK: stop reason = breakpoint 1.1
         ^
<stdin>:9:61: note: scanning from here
Breakpoint 1: where = windows-unaligned-x86_64.test.tmp`func at windows-unaligned-x86_64.cpp:3, address = 0x0000000140001000
                                                            ^
<stdin>:13:14: note: possible intended match here
* thread #1, stop reason = breakpoint 1.2
             ^
```

Affected tests are:
```
  lldb-shell :: SymbolFile/NativePDB/local-variables.cpp
  lldb-shell :: SymbolFile/NativePDB/stack_unwinding01.cpp
  lldb-shell :: Unwind/windows-unaligned-x86_64.test
```

See: https://github.com/swiftlang/swift/pull/76894#issuecomment-2441139173
Neither my local build nor the upstream bots seem to reproduce this failure.

**Comment by weliveindetail** [comment]
Failure of `lang/c/local_variables/TestLocalVariables.py` looks similar
```
FAIL: test_c_local_variables_dwarf (TestLocalVariables.LocalVariablesTestCase)
   Test local variable value.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llvm-project\lldb\packages\Python\lldbsuite\test\lldbtest.py", line 1768, in test_method
    return attrvalue(self)
  File "C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llvm-project\lldb\test\API\lang\c\local_variables\TestLocalVariables.py", line 47, in test_c_local_variables
    lldbutil.check_breakpoint(self, bpno=1, expected_hit_count=1)
  File "C:\Users\swift-ci\jenkins\workspace\swift-PR-windows\llvm-project\lldb\packages\Python\lldbsuite\test\lldbutil.py", line 717, in check_breakpoint
    test.assertEqual(expected_resolved_count, bkpt.GetNumResolvedLocations())
AssertionError: 2 != 1
Config=x86_64-T:\5\bin\clang.exe
----------------------------------------------------------------------
```
